module.exports = {
    autoprefixer: require('gulp-autoprefixer'),
    browserSync: require('browser-sync'),
    cache : require('gulp-cached'),
    changed : require('gulp-changed'),
    concat: require('gulp-concat'),
    crypto : require('crypto'),
    cssTimeStamp : require('gulp-timestamp-css-url'),
    del : require('del'),
    gulpIf: require("gulp-if"),
    imagemin : require('gulp-imagemin'),
    imageminGif : require('imagemin-gifsicle'),
    imageminJpg : require('imagemin-jpeg-recompress'),
    imageminPng : require('imagemin-pngquant'),
    plumber: require("gulp-plumber"),
    postcss: require('gulp-postcss'),
    postcssResponsiveFont: require('postcss-responsive-font'),
    pug: require('gulp-pug'),
    replace: require('gulp-replace'),
    stylus: require('gulp-stylus'),
    rename: require('gulp-rename'),
    webpack : require("webpack"),
    webpackStream : require("webpack-stream")
};

